<?php

/**
 * This file generated by Mezzio\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via mezzio-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            Sync\Commands\HowTime::class => Sync\Factories\CommandFactories\HowTimeCommandFactory::class,
            Sync\Commands\UpdateAccesses::class => Sync\Factories\CommandFactories\UpdateAccessesCommandFactory::class,
            
            Sync\Handlers\WidgetHandler::class => Sync\Factories\WidgetHandlerFactory::class,
            Sync\Handlers\AccountsHandler::class => Sync\Factories\AccountsHandlerFactory::class,
            Sync\Handlers\CreateIntegrationHandler::class => Sync\Factories\CreateIntegrationHandlerFactory::class,
            Sync\Handlers\SendContactsFromKommoHandler::class => Sync\Factories\SendContactsFromKommoHandlerFactory::class,
            Sync\Handlers\GetContactFromUnisenderHandler::class => Sync\Factories\GetContactFromUnisenderHandlerFactory::class,
            Sync\Handlers\KommoWebHookHandler::class => Sync\Factories\KommoWebHookHandlerFactory::class,
            Sync\Handlers\PingUnisenderHandler::class => Sync\Factories\PingUnisenderHandlerFactory::class,
            Sync\Handlers\AuthCallbackHandler::class => Sync\Factories\AuthCallbackHandlerFactory::class,
            Sync\Handlers\ContactsHandler::class => Sync\Factories\ContactsHandlerFactory::class,
        ],
    ],
];
